export const odcTarget = {
  id: 'odc',
  label: 'OutSystems Developer Cloud',
  lanes: ['reactive-web', 'mobile-webview'],
  scriptFormat: 'iife',
  javascriptTarget: 'es2017',
  lifecycle: {
    create: 'OnReady',
    update: ['OnParametersChanged', 'OnRender'],
    dispose: 'OnDestroy',
  },
  capabilities: { globalScripts: true, externalCss: true, requiresModuleLoader: false },
  browserApis: [
    'Document',
    'HTMLElement',
    'KeyboardEvent',
    'String.normalize',
    'Element.scrollIntoView',
    'Element.replaceChildren',
    'HTMLElement.focus',
    'HTMLElement.inert',
    'Navigator.platform',
    'MutationObserver',
    'ResizeObserver',
    'IntersectionObserver',
    'requestAnimationFrame',
    'Worker',
  ],
  overrides: [],
  rationale: 'Shared browser implementation. Independent target metadata and host verification.',
} as const;
